baseURL = "https://james.me"
languageCode = "en-us"
title = "James Issac"
theme = "beautifulhugo"

[Params]

homeTitle = "Hi! I'm James."
subtitle = "Thanks for dropping by. Here are some technical and creative things I'm interested in."
logo="/imgs/tiger.jpg"
dateFormat = "January 2, 2018"

[Author]
name="James Issac"
github="jissac"
twitter="james_issac_"
linkedin="jissac1"

[[menu.main]]
    name = "Tags"
    subtitle = "stuff"
    url = "tags"
    weight = 1

[[menu.main]]
    name = "Blog"
    url = "/post/first-post"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = ""
    weight = 1

[[menu.main]]
    name = "Photos"
    url = ""
    weight = 1

[[menu.main]]
    name = "Books"
    url = ""
    weight = 1
